"""ThemeAdapter — derive ~/.config/camfx/gtk.css from Omarchy's colors.toml + shell.toml.

Source of truth (docs/theming.md, themes/tokyo-night/colors.toml):
  ~/.local/state/omarchy/current/theme/colors.toml
  ~/.local/state/omarchy/current/theme/shell.toml (optional, not required for GTK)
Output:
  ~/.config/camfx/gtk.css                — GTK4 CSS watched live by camfx/gui/main_window.py:Gio.FileMonitor (Q7)
  ~/.config/camfx/icon-theme.css (opt)  — if icons.theme present

Rendering is minimal and additive — no default/themed/*.tpl mutation, so
INSTALLED_THEME_DENIED / test/shell.d/theme-staging-test.sh stays green.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger("camfx_omarchy.theme_adapter")

try:
	import tomllib  # 3.11+
except ImportError:
	import tomli as tomllib  # type: ignore[no-redef]


CSS_PATH = Path.home() / ".config" / "camfx" / "gtk.css"
THEME_CSS_PATH: Path | None = None  # reserved for future ~/.local/state/omarchy/current/theme/camfx.css tpl path


def _theme_dir(theme_name: str | None = None) -> Path:
	if theme_name:
		# Resolve by slug — search OMARCHY_PATH + ~/.config/omarchy/themes
		# For now, only current theme is needed (hook passes $1 for info, but CSS derives from current)
		from .omarchy_detection import current_theme_dir
		return current_theme_dir()
	from .omarchy_detection import current_theme_dir
	return current_theme_dir()


def load_colors(theme_dir: Path | None = None) -> dict[str, str]:
	"""Read colors.toml into dict[str, hex]. Returns {} if missing."""
	if theme_dir is None:
		theme_dir = _theme_dir()
	cpath = theme_dir / "colors.toml"
	if not cpath.exists():
		logger.warning("colors.toml not found at %s", cpath)
		return {}
	try:
		with cpath.open("rb") as f:
			data = tomllib.load(f)
		# Flatten any non-string values (ignore tables for now — colors are top-level keys)
		colors: dict[str, str] = {}
		for k, v in data.items():
			if isinstance(v, str):
				colors[k] = v
			elif isinstance(v, (int, float)):
				colors[k] = str(v)
		return colors
	except Exception as e:
		logger.warning("Failed to load colors.toml %s: %s", cpath, e)
		return {}


def render_gtk_css(colors: dict[str, str], template: str | None = None) -> str:
	"""Render GTK4 CSS from Omarchy palette.

	If template is given, render it via {{ key }} substitution (matches default/themed/*.tpl style).
	Otherwise use the compact built-in mapping covering window, button, label, accent.

	Keys referenced (canonical): background, foreground, accent, muted, selection,
	red/green/yellow/blue/magenta/cyan plus dark_/light_/bright_ variants if present.
	Legacy bg/fg aliases are supported via caller normalization but not required here.
	"""
	if template is not None:
		# Simple {{ key }} replacer
		css = template
		for k, v in colors.items():
			css = css.replace("{{ " + k + " }}", v).replace("{{" + k + "}}", v)
			css = css.replace("{{ " + k + "_strip }}", v.lstrip("#"))
		return css

	bg = colors.get("background", "#1a1b26")
	fg = colors.get("foreground", "#a9b1d6")
	accent = colors.get("accent", colors.get("color4", "#7aa2f7"))
	muted = colors.get("muted", colors.get("color8", "#414868"))
	selection = colors.get("selection", colors.get("selection_background", "#292e42"))
	# Derive a few more for completeness, fallback to bg/fg
	red = colors.get("red", "#f7768e")

	# Keep it short but cover the GUI's likely selectors (window, button.suggested-action, label.dim, error)
	return f"""/* camfx — generated by camfx_omarchy.theme_adapter from Omarchy colors.toml */
/* Do not edit — regenerated on `omarchy theme set` via ~/.config/omarchy/hooks/theme-set.d/50-camfx.sh */
@define-color camfx_bg {bg};
@define-color camfx_fg {fg};
@define-color camfx_accent {accent};
@define-color camfx_muted {muted};
@define-color camfx_selection {selection};
@define-color camfx_error {red};

window.background {{ background-color: {bg}; color: {fg}; }}
button.suggested-action {{ background: {accent}; color: {bg}; }}
button.suggested-action:hover {{ background: {selection}; }}
label.dim {{ color: {muted}; }}
.error {{ color: {red}; }}
.success {{ color: {accent}; }}
"""


def apply(theme_name: str | None = None, css_path: Path | None = None) -> Path:
	"""Read current Omarchy theme colors and write GTK CSS. Returns path written.

	Also `touch`es the file so Gio.FileMonitor in camfx gui live-reloads (Q7).
	"""
	if css_path is None:
		import os
		ov = os.environ.get("CAMFX_GTK_CSS")
		css_path = Path(ov) if ov else CSS_PATH
	css_path = Path(css_path)
	theme_dir = _theme_dir(theme_name)
	colors = load_colors(theme_dir)
	css = render_gtk_css(colors)
	try:
		css_path.parent.mkdir(parents=True, exist_ok=True)
		css_path.write_text(css, encoding="utf-8")
		# touch ensures monitor fires even if write time resolution is 1s
		try:
			import os, time
			now = time.time()
			os.utime(css_path, (now, now))
		except Exception:
			pass
		logger.info("Wrote camfx GTK CSS to %s (theme: %s)", css_path, theme_name or theme_dir.name)
	except Exception as e:
		logger.warning("Failed to write GTK CSS to %s: %s", css_path, e)
		raise
	return css_path


if __name__ == "__main__":
	import argparse

	p = argparse.ArgumentParser(description="camfx Omarchy theme adapter")
	p.add_argument("--theme-name", default=None, help="Omarchy theme slug (informational)")
	args = p.parse_args()
	apply(args.theme_name)
	print(f"Wrote {CSS_PATH}")
